### ISSUE TITLE
how to generate swagger document  https://raw.githubusercontent.com/steamcleaner/swagger-grails/master/src/test/resources/author-controller.png

### ISSUE THREAD

**Issue by rushdis** [steamcleaner/swagger-grails#3]

**Comment by steamcleaner** [comment]
I've updated the README to include some extra information on how to access the swagger JSON.

>This plugin will only generate the JSON representation of your endpoints. You'll
need to implement your own [swagger-ui](https://github.com/swagger-api/swagger-ui) to consume the JSON.

>If your `UrlMappings` file includes the default `"/$controller/$action?/$id?(.$format)?"` mapping then
the JSON will be acessible by hitting http://localhost:8080/swagger/api.  This endpoint
can be customized by adding `"/custom/swagger/endpoint"(controller: "swagger", action: "api")` to your
UrlMappings file.
