### ISSUE TITLE
No request body edit textarea appears on POST endpoint

### ISSUE THREAD

**Issue by xqliu** [steamcleaner/swagger-grails#7]
Hi,  thanks for your great work on the plugin :)

I have found an issue that, there's no request body edit textarea appears on POST endpoint

as per attached

![image](https://user-images.githubusercontent.com/22554/118843966-2318da00-b8fd-11eb-8238-6c161479cb5e.png)

While for normal post controller, it renders like follow(There's a textarea where request body json content could be input)

<img width="1463" alt="Screenshot 2021-05-20 at 12 00 16 AM" src="https://user-images.githubusercontent.com/22554/118845461-6293f600-b8fe-11eb-874b-636687ee8b25.png">

I am using swagger-ui-react(https://www.npmjs.com/package/swagger-ui-react) to generate the UI based on json file generated by swagger-grails.

I have attached the generated meta data for the API as below

![image](https://user-images.githubusercontent.com/22554/118844405-83a81700-b8fd-11eb-81dc-e7e4b5e93599.png)

Seems because grails has no @RequestBody annotation, so request body was not generated as a parameter, so swagger-ui didn't render the textarea for post request body.

I have tried to add a @RequestBody to controller method parameter, and the textarea can be generated as expected, but seems grails can not do the value binding correctly.

Not sure whether I have expressed the issue clearly...

**Comment by xqliu** [comment]
I think for a controller method with POST http method enable, an implicitly request body parameter  could be added to parameter list. since for grails, sometimes we just use `request.JSON` to get request body, without define any explicit method parameter.

**Comment by xqliu** [comment]
Also there's no request parameter input for get request which consumes param.xxxx (request query parameter)

**Comment by steamcleaner** [comment]
__Would it be possible for you to create an example project that I can reproduce the issue?__

Also, you can apply Swagger annotations to the actions in controllers to adjust how the UI is built.
For example, you can have the UI render a body input for an action that doesn't have any fields defined in the method declaration:

```
    @ApiImplicitParams([
            @ApiImplicitParam(
                    name = "json",
                    paramType = "body",
                    required = true,
                    value = "json",
                    dataType = "java.util.HashMap"
            )
    ])
    @ApiOperation(value = "custom", nickname = "/your/route", httpMethod = "POST")
    def custom() {
        println(request.JSON)
    }
```

The [PublisherController](https://github.com/steamcleaner/swagger-grails/blob/master/grails-app/controllers/swagger/grails/test/PublisherController.groovy#L29) also has an example of how to attach custom query params.

**Comment by xqliu** [comment]
Hi, Thanks for your information.

For the query parameter, I have added them explicitly as parameters to my controller methods. and then they appear in UI.

For the post body parameter, I confirmed your suggestion works.

But seems put ApiParam to method parameter like below, the value of @ApiParam didn't render on frontend.

``` java
  @ApiImplicitParams([
    @ApiImplicitParam(
      name = "domainJson",
      paramType = "body",
      required = true,
      value = "JSON represent of domain properties",
      dataType = "java.util.HashMap"
    )])
  @Transactional
  def update(String domainName, @ApiParam(value = "domain id") Long id) {
```
This is what rendered on swagger-ui, you can see the ApiImplicitParam value actually rendered correctly, but the @ApiParam value didn't render.

<img width="1465" alt="Screenshot 2021-05-21 at 4 39 48 PM" src="https://user-images.githubusercontent.com/22554/119108845-3938ae80-ba53-11eb-996a-ef093ddc28b3.png">

Thanks for your great help :)

**Comment by steamcleaner** [comment]
The plugin doesn't look at any annotations that are defined on the method parameters. 

Might be able to use an `@ApiImplicitParam` with a `paramType="path"` to allow adjustment of the domain id.

**Comment by xqliu** [comment]
Thanks for your clarification :) thanks again for your work on the package :)
